# Generated by Django 4.2.4 on 2023-08-31 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_alter_blogcreatemodel_body_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogcreatemodel',
            name='image',
            field=models.ImageField(height_field='150', upload_to='blog_image', verbose_name='Фото', width_field='250'),
        ),
    ]
