# Generated by Django 4.2.4 on 2023-09-01 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_alter_blogcreatemodel_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogcreatemodel',
            name='image',
            field=models.ImageField(upload_to='blog_image', verbose_name='Фото'),
        ),
        migrations.AlterField(
            model_name='blogcreatemodel',
            name='slug',
            field=models.SlugField(unique=True),
        ),
        migrations.AlterField(
            model_name='blogcreatemodel',
            name='title',
            field=models.CharField(max_length=50, verbose_name='Название статьи'),
        ),
    ]
