# Generated by Django 4.2.4 on 2023-09-09 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('furnitures', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='furnituresmodel',
            options={'verbose_name': 'Furniture'},
        ),
        migrations.AlterField(
            model_name='furnituresmodel',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=6),
        ),
    ]
